### ISSUE TITLE
Integration into inkscape

### ISSUE THREAD

**Issue by vmario89** [tatarize/vpype-dxf#2]
hey, just wanted to let you know that i built in vpype-dxf as one option of my DXF/DWG Importer for InkScape: https://stadtfabrikanten.org/pages/viewpage.action?pageId=78807535
code of the extension can be found at https://gitea.fablabchemnitz.de/MarioVoigt/mightyscape-1.X/src/branch/master/extensions/fablabchemnitz/dxfdwgimporter

regards, Mario

**Comment by tatarize** [comment]
ODA got a particular file right that I never figured out how it managed that. Somewhere in the discord drawingbots discord after vpype-dxf was built there was a long parsing process of some kind of gothic electric output that used some weird non-standard algorithm and ODA was literally the only thing that seemed to get it right, though vpype-dxf wasn't too far off from that.  That shotgun approach might be about right.
